/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedHostRouteImport } from './routes/_authenticated/host'
import { Route as AuthenticatedTripsRouteImport } from './routes/_authenticated/trips'
import { Route as PropertyIdRouteImport } from './routes/property.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedHostNewRouteImport } from './routes/_authenticated/host.new'
import { Route as ApiPublicHooksMpesaCallbackRouteImport } from './routes/api/public/hooks/mpesa-callback'
import { Route as ApiPublicHooksSyncListingsRouteImport } from './routes/api/public/hooks/sync-listings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHostRoute = AuthenticatedHostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTripsRoute = AuthenticatedTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedHostNewRoute = AuthenticatedHostNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedHostRoute,
} as any)
const ApiPublicHooksMpesaCallbackRoute =
  ApiPublicHooksMpesaCallbackRouteImport.update({
    id: '/api/public/hooks/mpesa-callback',
    path: '/api/public/hooks/mpesa-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncListingsRoute =
  ApiPublicHooksSyncListingsRouteImport.update({
    id: '/api/public/hooks/sync-listings',
    path: '/api/public/hooks/sync-listings',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/account': typeof AuthenticatedAccountRoute
  '/host': typeof AuthenticatedHostRouteWithChildren
  '/trips': typeof AuthenticatedTripsRoute
  '/property/$id': typeof PropertyIdRoute
  '/host/new': typeof AuthenticatedHostNewRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/mpesa-callback': typeof ApiPublicHooksMpesaCallbackRoute
  '/api/public/hooks/sync-listings': typeof ApiPublicHooksSyncListingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/account': typeof AuthenticatedAccountRoute
  '/host': typeof AuthenticatedHostRouteWithChildren
  '/trips': typeof AuthenticatedTripsRoute
  '/property/$id': typeof PropertyIdRoute
  '/host/new': typeof AuthenticatedHostNewRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/mpesa-callback': typeof ApiPublicHooksMpesaCallbackRoute
  '/api/public/hooks/sync-listings': typeof ApiPublicHooksSyncListingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/host': typeof AuthenticatedHostRouteWithChildren
  '/_authenticated/trips': typeof AuthenticatedTripsRoute
  '/property/$id': typeof PropertyIdRoute
  '/_authenticated/host/new': typeof AuthenticatedHostNewRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/mpesa-callback': typeof ApiPublicHooksMpesaCallbackRoute
  '/api/public/hooks/sync-listings': typeof ApiPublicHooksSyncListingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/search'
    | '/admin'
    | '/account'
    | '/host'
    | '/trips'
    | '/property/$id'
    | '/host/new'
    | '/admin/'
    | '/api/public/hooks/mpesa-callback'
    | '/api/public/hooks/sync-listings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/search'
    | '/account'
    | '/host'
    | '/trips'
    | '/property/$id'
    | '/host/new'
    | '/admin'
    | '/api/public/hooks/mpesa-callback'
    | '/api/public/hooks/sync-listings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/search'
    | '/_authenticated/admin'
    | '/_authenticated/account'
    | '/_authenticated/host'
    | '/_authenticated/trips'
    | '/property/$id'
    | '/_authenticated/host/new'
    | '/_authenticated/admin/'
    | '/api/public/hooks/mpesa-callback'
    | '/api/public/hooks/sync-listings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SearchRoute: typeof SearchRoute
  PropertyIdRoute: typeof PropertyIdRoute
  ApiPublicHooksMpesaCallbackRoute: typeof ApiPublicHooksMpesaCallbackRoute
  ApiPublicHooksSyncListingsRoute: typeof ApiPublicHooksSyncListingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/host': {
      id: '/_authenticated/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof AuthenticatedHostRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trips': {
      id: '/_authenticated/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AuthenticatedTripsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/host/new': {
      id: '/_authenticated/host/new'
      path: '/new'
      fullPath: '/host/new'
      preLoaderRoute: typeof AuthenticatedHostNewRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/api/public/hooks/mpesa-callback': {
      id: '/api/public/hooks/mpesa-callback'
      path: '/api/public/hooks/mpesa-callback'
      fullPath: '/api/public/hooks/mpesa-callback'
      preLoaderRoute: typeof ApiPublicHooksMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-listings': {
      id: '/api/public/hooks/sync-listings'
      path: '/api/public/hooks/sync-listings'
      fullPath: '/api/public/hooks/sync-listings'
      preLoaderRoute: typeof ApiPublicHooksSyncListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedHostRouteChildren {
  AuthenticatedHostNewRoute: typeof AuthenticatedHostNewRoute
}

const AuthenticatedHostRouteChildren: AuthenticatedHostRouteChildren = {
  AuthenticatedHostNewRoute: AuthenticatedHostNewRoute,
}

const AuthenticatedHostRouteWithChildren =
  AuthenticatedHostRoute._addFileChildren(AuthenticatedHostRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedHostRoute: typeof AuthenticatedHostRouteWithChildren
  AuthenticatedTripsRoute: typeof AuthenticatedTripsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedHostRoute: AuthenticatedHostRouteWithChildren,
  AuthenticatedTripsRoute: AuthenticatedTripsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SearchRoute: SearchRoute,
  PropertyIdRoute: PropertyIdRoute,
  ApiPublicHooksMpesaCallbackRoute: ApiPublicHooksMpesaCallbackRoute,
  ApiPublicHooksSyncListingsRoute: ApiPublicHooksSyncListingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
