/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedHostRouteImport } from './routes/_authenticated/host'
import { Route as AuthenticatedPayoutsRouteImport } from './routes/_authenticated/payouts'
import { Route as AuthenticatedTripsRouteImport } from './routes/_authenticated/trips'
import { Route as PropertyIdRouteImport } from './routes/property.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminMpesaLogsRouteImport } from './routes/_authenticated/admin/mpesa-logs'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedHostNewRouteImport } from './routes/_authenticated/host.new'
import { Route as ApiPublicHooksIpayCallbackRouteImport } from './routes/api/public/hooks/ipay-callback'
import { Route as ApiPublicHooksMpesaB2cResultRouteImport } from './routes/api/public/hooks/mpesa-b2c-result'
import { Route as ApiPublicHooksMpesaB2cTimeoutRouteImport } from './routes/api/public/hooks/mpesa-b2c-timeout'
import { Route as ApiPublicHooksMpesaCallbackRouteImport } from './routes/api/public/hooks/mpesa-callback'
import { Route as ApiPublicHooksPayCallbackRouteImport } from './routes/api/public/hooks/pay-callback'
import { Route as ApiPublicHooksPayoutResultRouteImport } from './routes/api/public/hooks/payout-result'
import { Route as ApiPublicHooksPayoutTimeoutRouteImport } from './routes/api/public/hooks/payout-timeout'
import { Route as ApiPublicHooksSyncListingsRouteImport } from './routes/api/public/hooks/sync-listings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHostRoute = AuthenticatedHostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayoutsRoute = AuthenticatedPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTripsRoute = AuthenticatedTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminMpesaLogsRoute =
  AuthenticatedAdminMpesaLogsRouteImport.update({
    id: '/mpesa-logs',
    path: '/mpesa-logs',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedHostNewRoute = AuthenticatedHostNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedHostRoute,
} as any)
const ApiPublicHooksIpayCallbackRoute =
  ApiPublicHooksIpayCallbackRouteImport.update({
    id: '/api/public/hooks/ipay-callback',
    path: '/api/public/hooks/ipay-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMpesaB2cResultRoute =
  ApiPublicHooksMpesaB2cResultRouteImport.update({
    id: '/api/public/hooks/mpesa-b2c-result',
    path: '/api/public/hooks/mpesa-b2c-result',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMpesaB2cTimeoutRoute =
  ApiPublicHooksMpesaB2cTimeoutRouteImport.update({
    id: '/api/public/hooks/mpesa-b2c-timeout',
    path: '/api/public/hooks/mpesa-b2c-timeout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMpesaCallbackRoute =
  ApiPublicHooksMpesaCallbackRouteImport.update({
    id: '/api/public/hooks/mpesa-callback',
    path: '/api/public/hooks/mpesa-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPayCallbackRoute =
  ApiPublicHooksPayCallbackRouteImport.update({
    id: '/api/public/hooks/pay-callback',
    path: '/api/public/hooks/pay-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPayoutResultRoute =
  ApiPublicHooksPayoutResultRouteImport.update({
    id: '/api/public/hooks/payout-result',
    path: '/api/public/hooks/payout-result',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPayoutTimeoutRoute =
  ApiPublicHooksPayoutTimeoutRouteImport.update({
    id: '/api/public/hooks/payout-timeout',
    path: '/api/public/hooks/payout-timeout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncListingsRoute =
  ApiPublicHooksSyncListingsRouteImport.update({
    id: '/api/public/hooks/sync-listings',
    path: '/api/public/hooks/sync-listings',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/faqs': typeof FaqsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/account': typeof AuthenticatedAccountRoute
  '/host': typeof AuthenticatedHostRouteWithChildren
  '/payouts': typeof AuthenticatedPayoutsRoute
  '/trips': typeof AuthenticatedTripsRoute
  '/property/$id': typeof PropertyIdRoute
  '/admin/mpesa-logs': typeof AuthenticatedAdminMpesaLogsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/host/new': typeof AuthenticatedHostNewRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/ipay-callback': typeof ApiPublicHooksIpayCallbackRoute
  '/api/public/hooks/mpesa-b2c-result': typeof ApiPublicHooksMpesaB2cResultRoute
  '/api/public/hooks/mpesa-b2c-timeout': typeof ApiPublicHooksMpesaB2cTimeoutRoute
  '/api/public/hooks/mpesa-callback': typeof ApiPublicHooksMpesaCallbackRoute
  '/api/public/hooks/pay-callback': typeof ApiPublicHooksPayCallbackRoute
  '/api/public/hooks/payout-result': typeof ApiPublicHooksPayoutResultRoute
  '/api/public/hooks/payout-timeout': typeof ApiPublicHooksPayoutTimeoutRoute
  '/api/public/hooks/sync-listings': typeof ApiPublicHooksSyncListingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/faqs': typeof FaqsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/host': typeof AuthenticatedHostRouteWithChildren
  '/payouts': typeof AuthenticatedPayoutsRoute
  '/trips': typeof AuthenticatedTripsRoute
  '/property/$id': typeof PropertyIdRoute
  '/admin/mpesa-logs': typeof AuthenticatedAdminMpesaLogsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/host/new': typeof AuthenticatedHostNewRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/ipay-callback': typeof ApiPublicHooksIpayCallbackRoute
  '/api/public/hooks/mpesa-b2c-result': typeof ApiPublicHooksMpesaB2cResultRoute
  '/api/public/hooks/mpesa-b2c-timeout': typeof ApiPublicHooksMpesaB2cTimeoutRoute
  '/api/public/hooks/mpesa-callback': typeof ApiPublicHooksMpesaCallbackRoute
  '/api/public/hooks/pay-callback': typeof ApiPublicHooksPayCallbackRoute
  '/api/public/hooks/payout-result': typeof ApiPublicHooksPayoutResultRoute
  '/api/public/hooks/payout-timeout': typeof ApiPublicHooksPayoutTimeoutRoute
  '/api/public/hooks/sync-listings': typeof ApiPublicHooksSyncListingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/faqs': typeof FaqsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/host': typeof AuthenticatedHostRouteWithChildren
  '/_authenticated/payouts': typeof AuthenticatedPayoutsRoute
  '/_authenticated/trips': typeof AuthenticatedTripsRoute
  '/property/$id': typeof PropertyIdRoute
  '/_authenticated/admin/mpesa-logs': typeof AuthenticatedAdminMpesaLogsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/host/new': typeof AuthenticatedHostNewRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/ipay-callback': typeof ApiPublicHooksIpayCallbackRoute
  '/api/public/hooks/mpesa-b2c-result': typeof ApiPublicHooksMpesaB2cResultRoute
  '/api/public/hooks/mpesa-b2c-timeout': typeof ApiPublicHooksMpesaB2cTimeoutRoute
  '/api/public/hooks/mpesa-callback': typeof ApiPublicHooksMpesaCallbackRoute
  '/api/public/hooks/pay-callback': typeof ApiPublicHooksPayCallbackRoute
  '/api/public/hooks/payout-result': typeof ApiPublicHooksPayoutResultRoute
  '/api/public/hooks/payout-timeout': typeof ApiPublicHooksPayoutTimeoutRoute
  '/api/public/hooks/sync-listings': typeof ApiPublicHooksSyncListingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/faqs'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/account'
    | '/host'
    | '/payouts'
    | '/trips'
    | '/property/$id'
    | '/admin/mpesa-logs'
    | '/admin/settings'
    | '/host/new'
    | '/admin/'
    | '/api/public/hooks/ipay-callback'
    | '/api/public/hooks/mpesa-b2c-result'
    | '/api/public/hooks/mpesa-b2c-timeout'
    | '/api/public/hooks/mpesa-callback'
    | '/api/public/hooks/pay-callback'
    | '/api/public/hooks/payout-result'
    | '/api/public/hooks/payout-timeout'
    | '/api/public/hooks/sync-listings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/faqs'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/account'
    | '/host'
    | '/payouts'
    | '/trips'
    | '/property/$id'
    | '/admin/mpesa-logs'
    | '/admin/settings'
    | '/host/new'
    | '/admin'
    | '/api/public/hooks/ipay-callback'
    | '/api/public/hooks/mpesa-b2c-result'
    | '/api/public/hooks/mpesa-b2c-timeout'
    | '/api/public/hooks/mpesa-callback'
    | '/api/public/hooks/pay-callback'
    | '/api/public/hooks/payout-result'
    | '/api/public/hooks/payout-timeout'
    | '/api/public/hooks/sync-listings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/faqs'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/account'
    | '/_authenticated/host'
    | '/_authenticated/payouts'
    | '/_authenticated/trips'
    | '/property/$id'
    | '/_authenticated/admin/mpesa-logs'
    | '/_authenticated/admin/settings'
    | '/_authenticated/host/new'
    | '/_authenticated/admin/'
    | '/api/public/hooks/ipay-callback'
    | '/api/public/hooks/mpesa-b2c-result'
    | '/api/public/hooks/mpesa-b2c-timeout'
    | '/api/public/hooks/mpesa-callback'
    | '/api/public/hooks/pay-callback'
    | '/api/public/hooks/payout-result'
    | '/api/public/hooks/payout-timeout'
    | '/api/public/hooks/sync-listings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FaqsRoute: typeof FaqsRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  PropertyIdRoute: typeof PropertyIdRoute
  ApiPublicHooksIpayCallbackRoute: typeof ApiPublicHooksIpayCallbackRoute
  ApiPublicHooksMpesaB2cResultRoute: typeof ApiPublicHooksMpesaB2cResultRoute
  ApiPublicHooksMpesaB2cTimeoutRoute: typeof ApiPublicHooksMpesaB2cTimeoutRoute
  ApiPublicHooksMpesaCallbackRoute: typeof ApiPublicHooksMpesaCallbackRoute
  ApiPublicHooksPayCallbackRoute: typeof ApiPublicHooksPayCallbackRoute
  ApiPublicHooksPayoutResultRoute: typeof ApiPublicHooksPayoutResultRoute
  ApiPublicHooksPayoutTimeoutRoute: typeof ApiPublicHooksPayoutTimeoutRoute
  ApiPublicHooksSyncListingsRoute: typeof ApiPublicHooksSyncListingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/host': {
      id: '/_authenticated/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof AuthenticatedHostRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payouts': {
      id: '/_authenticated/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof AuthenticatedPayoutsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trips': {
      id: '/_authenticated/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AuthenticatedTripsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/mpesa-logs': {
      id: '/_authenticated/admin/mpesa-logs'
      path: '/mpesa-logs'
      fullPath: '/admin/mpesa-logs'
      preLoaderRoute: typeof AuthenticatedAdminMpesaLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/host/new': {
      id: '/_authenticated/host/new'
      path: '/new'
      fullPath: '/host/new'
      preLoaderRoute: typeof AuthenticatedHostNewRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/api/public/hooks/ipay-callback': {
      id: '/api/public/hooks/ipay-callback'
      path: '/api/public/hooks/ipay-callback'
      fullPath: '/api/public/hooks/ipay-callback'
      preLoaderRoute: typeof ApiPublicHooksIpayCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/mpesa-b2c-result': {
      id: '/api/public/hooks/mpesa-b2c-result'
      path: '/api/public/hooks/mpesa-b2c-result'
      fullPath: '/api/public/hooks/mpesa-b2c-result'
      preLoaderRoute: typeof ApiPublicHooksMpesaB2cResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/mpesa-b2c-timeout': {
      id: '/api/public/hooks/mpesa-b2c-timeout'
      path: '/api/public/hooks/mpesa-b2c-timeout'
      fullPath: '/api/public/hooks/mpesa-b2c-timeout'
      preLoaderRoute: typeof ApiPublicHooksMpesaB2cTimeoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/mpesa-callback': {
      id: '/api/public/hooks/mpesa-callback'
      path: '/api/public/hooks/mpesa-callback'
      fullPath: '/api/public/hooks/mpesa-callback'
      preLoaderRoute: typeof ApiPublicHooksMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/pay-callback': {
      id: '/api/public/hooks/pay-callback'
      path: '/api/public/hooks/pay-callback'
      fullPath: '/api/public/hooks/pay-callback'
      preLoaderRoute: typeof ApiPublicHooksPayCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/payout-result': {
      id: '/api/public/hooks/payout-result'
      path: '/api/public/hooks/payout-result'
      fullPath: '/api/public/hooks/payout-result'
      preLoaderRoute: typeof ApiPublicHooksPayoutResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/payout-timeout': {
      id: '/api/public/hooks/payout-timeout'
      path: '/api/public/hooks/payout-timeout'
      fullPath: '/api/public/hooks/payout-timeout'
      preLoaderRoute: typeof ApiPublicHooksPayoutTimeoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-listings': {
      id: '/api/public/hooks/sync-listings'
      path: '/api/public/hooks/sync-listings'
      fullPath: '/api/public/hooks/sync-listings'
      preLoaderRoute: typeof ApiPublicHooksSyncListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminMpesaLogsRoute: typeof AuthenticatedAdminMpesaLogsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminMpesaLogsRoute: AuthenticatedAdminMpesaLogsRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedHostRouteChildren {
  AuthenticatedHostNewRoute: typeof AuthenticatedHostNewRoute
}

const AuthenticatedHostRouteChildren: AuthenticatedHostRouteChildren = {
  AuthenticatedHostNewRoute: AuthenticatedHostNewRoute,
}

const AuthenticatedHostRouteWithChildren =
  AuthenticatedHostRoute._addFileChildren(AuthenticatedHostRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedHostRoute: typeof AuthenticatedHostRouteWithChildren
  AuthenticatedPayoutsRoute: typeof AuthenticatedPayoutsRoute
  AuthenticatedTripsRoute: typeof AuthenticatedTripsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedHostRoute: AuthenticatedHostRouteWithChildren,
  AuthenticatedPayoutsRoute: AuthenticatedPayoutsRoute,
  AuthenticatedTripsRoute: AuthenticatedTripsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FaqsRoute: FaqsRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  PropertyIdRoute: PropertyIdRoute,
  ApiPublicHooksIpayCallbackRoute: ApiPublicHooksIpayCallbackRoute,
  ApiPublicHooksMpesaB2cResultRoute: ApiPublicHooksMpesaB2cResultRoute,
  ApiPublicHooksMpesaB2cTimeoutRoute: ApiPublicHooksMpesaB2cTimeoutRoute,
  ApiPublicHooksMpesaCallbackRoute: ApiPublicHooksMpesaCallbackRoute,
  ApiPublicHooksPayCallbackRoute: ApiPublicHooksPayCallbackRoute,
  ApiPublicHooksPayoutResultRoute: ApiPublicHooksPayoutResultRoute,
  ApiPublicHooksPayoutTimeoutRoute: ApiPublicHooksPayoutTimeoutRoute,
  ApiPublicHooksSyncListingsRoute: ApiPublicHooksSyncListingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
